{'application': False,
 'assets': {'point_of_sale.assets': ['grupol7_liquidacion_qr/static/src/js/pos_coupon_boot.js']},
 'author': 'Grupo L7 / Implementación',
 'data': ['security/ir.model.access.csv',
          'report/liquidation_labels.xml',
          'views/liquidation_coupon_views.xml',
          'views/liq_coupon_location_views.xml',
          'views/liq_trace_views.xml',
          'views/menu_liq_root.xml',
          'views/report_liq_sales.xml'],
 'depends': ['base', 'sale', 'point_of_sale', 'stock', 'barcodes'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'Liquidación con QR (Cupones por pieza)',
 'summary': 'Cupones QR para liquidación: valida producto y precio, un solo uso, POS y Ventas, reporte por PdV.',
 'version': '16.0.1.79'}